package com;

public enum RejectionReasons {
	LOW_INCOME,
	NEGATIVE_CREDIT_HISTORY,
	WORKLESS_BORROWER,
	LOW_WORK_EXPERIENCE,
	PROFESSION_OF_BORROWER_IS_NOT_DEMAND,
	CLOSE_RELATIVE_HAS_BAD_CREDIT_HISTORY,
	LACK_OF_OWNERSHIP
}
